spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/rosa;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa :
    ddl-auto : create
    hibernate.naming_strategy : org.hibernate.cfg.EJB3NamingStrategy
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

management:
  context-path: /monitoring